#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FolderTree
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ImagesDB")]
	public partial class IMAGEDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public IMAGEDataContext() : 
				base(global::FolderTree.Properties.Settings.Default.ImagesDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public IMAGEDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IMAGEDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IMAGEDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IMAGEDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ADDIMAGE")]
		public int SP_ADDIMAGE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IMAGENAME", DbType="NVarChar(50)")] string iMAGENAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IMAGEEMAIL", DbType="NVarChar(50)")] string iMAGEEMAIL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IMAGEADDRESS", DbType="NVarChar(50)")] string iMAGEADDRESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IMAGEIMAGE", DbType="Image")] System.Data.Linq.Binary iMAGEIMAGE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iMAGENAME, iMAGEEMAIL, iMAGEADDRESS, iMAGEIMAGE);
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
